# Default values for namespace dev
deployment:
  image: 203271543287.dkr.ecr.eu-west-3.amazonaws.com/fastapi-traefik-app
  imagePullPolicy: Always
  tag: latest
  replicaCount: 1
  port: 8000
  dbName: fastapi
  dbEndPoint: db
  
service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

hpa:
  min: 1
  max: 2
  percent: 80

ingress:
  http_port: 8001
  https_port: 4443
