# Default values for fastapi.
deployment:
  image: pablohassan/fast-api-exo
  imagePullPolicy: Always
  tag: latest
  replicaCount: 2
  port: 8000
  dbName: fastapi
  dbEndPoint: db
  
service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

hpa:
  min: 4
  max: 6
  percent: 80

ingress:
  http_port: 80
  https_port: 443

